version: "3.9"
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    # volumes:
    #   - ./static:/code/static
    #   - ./media:/code/media
    depends_on:
      - web
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8001:8001
    command: gunicorn --bind 0.0.0.0:8001 nomad.wsgi
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env


volumes:
  postgres_data: