version: "3.9"
services:
  web:
    build: .
    # command: gunicorn --bind 0.0.0.0:8000 nomad.wsgi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
    ports:
      - "81:81"
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
